/*
 * DIO_cfg.c
 *
 *  Created on: Feb 8, 2025
 *      Author: kerel
 */

#include "DIO_interface.h"
#include "DIO_private.h"


const DioDirection_Type config_pins[NUM_OF_PINS]=
{
OUTPUT,	//	PA0
OUTPUT,			//	PA1
OUTPUT,	//	PA2
INPUT_FLOATING,	//	PA3
INPUT_FLOATING,	//	PA4
INPUT_FLOATING,	//	PA5
INPUT_FLOATING,	//	PA6
INPUT_FLOATING,	//	PA7
OUTPUT,	//	PB0
OUTPUT,	//	PB1
OUTPUT,	//	PB2
OUTPUT,	//	PB3
OUTPUT,	//	PB4
OUTPUT,	//	PB5
OUTPUT,	//	PB6
OUTPUT,	//	PB7
INPUT_FLOATING,	//	PC0
OUTPUT,	//	PC1
INPUT_FLOATING,	//	PC2
INPUT_FLOATING,	//	PC3
INPUT_FLOATING,	//	PC4
INPUT_FLOATING,	//	PC5
INPUT_FLOATING,	//	PC6
INPUT_FLOATING,	//	PC7
INPUT_FLOATING,	//	PD0
OUTPUT,	//	PD1
INPUT_FLOATING,	//	PD2
INPUT_FLOATING,	//	PD3
INPUT_FLOATING,	//	PD4
INPUT_FLOATING,	//	PD5
INPUT_FLOATING,	//	PD6
INPUT_FLOATING,	//	PD7
};
